# NumPy

	• NumPy is Python Library used for working with arrays.
	• NumPy stands for Numerical Python, used in linear algebra and Matrices.
     -> Array object in NumPy is called ndarray, 50x faster than list.
     
     https://drive.google.com/file/d/1gK9QXIT_VQDo3U6oUP9LE0lm12PkQIEC/view?usp=sharing
     
     

In [1]:
import numpy as np 

In [2]:
l = [1,2,3,4,5,6]

In [3]:
l1 = [4,5,6,7,"sudh" , 34.565, True]

In [4]:
a1 = np.array(l1)

In [5]:
a2 = np.array([[1,2,3] , [4,5,6]])

In [6]:
a3 = np.array([[[1,2,3] , [4,5,6] , [7,8,9]]])

In [7]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [8]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [10]:
a1.ndim

1

In [11]:
a2.ndim

2

In [12]:
a3.ndim

3

In [13]:
a2.size

6

In [14]:
a3.size

9

In [15]:
a2.shape

(2, 3)

In [16]:
a3.shape

(1, 3, 3)

In [17]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [18]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
np.random.randint(2,50 ,(2,3,4) )

array([[[24,  9,  2, 19],
        [48, 47, 46, 34],
        [47, 46, 21, 13]],

       [[15, 45, 34, 14],
        [49,  4, 28, 45],
        [46, 38,  4,  6]]])

In [21]:
import numpy as np
n = np.random.rand(5,4)

In [22]:
a4 =  np.random.randn(4,4) 

In [23]:
a4.reshape(8,2)

array([[ 0.666264  ,  0.89776418],
       [-0.84948701, -1.33549163],
       [ 0.68173793,  0.20339935],
       [-0.22756013,  0.82385846],
       [ 2.27976981, -1.49924541],
       [-1.39613423, -0.20619247],
       [-1.88542463, -0.38149456],
       [-1.38134102,  1.04160675]])

In [24]:
a4.reshape(16,1)

array([[ 0.666264  ],
       [ 0.89776418],
       [-0.84948701],
       [-1.33549163],
       [ 0.68173793],
       [ 0.20339935],
       [-0.22756013],
       [ 0.82385846],
       [ 2.27976981],
       [-1.49924541],
       [-1.39613423],
       [-0.20619247],
       [-1.88542463],
       [-0.38149456],
       [-1.38134102],
       [ 1.04160675]])

In [25]:
a4.reshape(2,-134564364)

array([[ 0.666264  ,  0.89776418, -0.84948701, -1.33549163,  0.68173793,
         0.20339935, -0.22756013,  0.82385846],
       [ 2.27976981, -1.49924541, -1.39613423, -0.20619247, -1.88542463,
        -0.38149456, -1.38134102,  1.04160675]])

In [26]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[ 0.666264  ,  0.89776418, -0.84948701,
                -1.33549163],
               [ 0.68173793,  0.20339935, -0.22756013,
                 0.82385846]],

              [[ 2.27976981, -1.49924541, -1.39613423,
                -0.20619247],
               [-1.88542463, -0.38149456, -1.38134102,
                 1.04160675]]]]]]]]]])

In [27]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [28]:
a1[0]

'4'

In [29]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [30]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [31]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [32]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [34]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [35]:
a2[[0,1] , 1:]

array([[2, 3],
       [5, 6]])

In [36]:
a5 = np.random.randint(2,90 , (6,5))

In [37]:
a5

array([[43, 53,  5, 60, 30],
       [36, 52, 62, 81, 24],
       [ 5, 20,  2, 17,  6],
       [61, 23, 51, 77, 34],
       [17, 36, 70, 53, 64],
       [82, 36, 39, 21,  9]])

In [38]:
a5

array([[43, 53,  5, 60, 30],
       [36, 52, 62, 81, 24],
       [ 5, 20,  2, 17,  6],
       [61, 23, 51, 77, 34],
       [17, 36, 70, 53, 64],
       [82, 36, 39, 21,  9]])

In [39]:
a5[0,1] = 100

In [40]:
a5

array([[ 43, 100,   5,  60,  30],
       [ 36,  52,  62,  81,  24],
       [  5,  20,   2,  17,   6],
       [ 61,  23,  51,  77,  34],
       [ 17,  36,  70,  53,  64],
       [ 82,  36,  39,  21,   9]])

In [41]:
a6 = np.random.randint(0,3 , (3,3))

In [42]:
a7 = np.random.randint(0,3 , (3,3))

In [43]:
a6

array([[2, 2, 2],
       [0, 0, 0],
       [1, 1, 0]])

In [44]:
a7



array([[2, 0, 2],
       [0, 2, 0],
       [0, 0, 0]])

In [45]:
a6*a7

array([[4, 0, 4],
       [0, 0, 0],
       [0, 0, 0]])

In [46]:
a6@a7

array([[4, 4, 4],
       [0, 0, 0],
       [2, 2, 2]])

In [47]:
a6

array([[2, 2, 2],
       [0, 0, 0],
       [1, 1, 0]])

In [48]:
a6+100

array([[102, 102, 102],
       [100, 100, 100],
       [101, 101, 100]])

In [49]:
a6*2

array([[4, 4, 4],
       [0, 0, 0],
       [2, 2, 0]])

In [50]:
a6/0

C:\Users\bsingh\AppData\Local\Temp\ipykernel_10652\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\bsingh\AppData\Local\Temp\ipykernel_10652\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, inf],
       [nan, nan, nan],
       [inf, inf, nan]])

In [51]:
a6

array([[2, 2, 2],
       [0, 0, 0],
       [1, 1, 0]])

In [52]:
a6**3


array([[8, 8, 8],
       [0, 0, 0],
       [1, 1, 0]], dtype=int32)

In [56]:
a9=a6**3

In [57]:
a9+10

array([[18, 18, 18],
       [10, 10, 10],
       [11, 11, 10]], dtype=int32)

In [58]:
a9

array([[8, 8, 8],
       [0, 0, 0],
       [1, 1, 0]], dtype=int32)

In [59]:
a9 + np.array([1,2,3,4,5])

ValueError: operands could not be broadcast together with shapes (3,3) (5,) 

In [60]:
a9

array([[8, 8, 8],
       [0, 0, 0],
       [1, 1, 0]], dtype=int32)

In [61]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [62]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [63]:
a6.T

array([[2, 0, 1],
       [2, 0, 1],
       [2, 0, 0]])

In [64]:
a6

array([[2, 2, 2],
       [0, 0, 0],
       [1, 1, 0]])

In [65]:
a5

array([[ 43, 100,   5,  60,  30],
       [ 36,  52,  62,  81,  24],
       [  5,  20,   2,  17,   6],
       [ 61,  23,  51,  77,  34],
       [ 17,  36,  70,  53,  64],
       [ 82,  36,  39,  21,   9]])

In [66]:
a1 = np.eye(3,3)
a2 = np.ones(3)

In [67]:
a1@a2

array([1., 1., 1.])

In [71]:
import cufflinks as cf 
import numpy as np
import pandas as pd 
import seaborn as sns



In [69]:
!pip install cufflinks

  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68736 sha256=e5478290a7c1cacc312be7f676cd61a88865a524b90ee0d568b76cc44a448adc
  Stored in directory: c:\users\bsingh\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks


In [72]:
cf.go_offline()

In [73]:
df = pd.DataFrame(np.random.randn(100,3),columns=['A' , 'B' ,'C'])

In [74]:
df

A         B         C
0   0.438656 -0.503832 -2.042863
1  -0.044595  1.072661  0.488996
2   1.408702 -1.083059  1.868867
3  -0.121024 -2.399767  0.239453
4   0.408174  0.726992  0.489874
..       ...       ...       ...
95 -2.729132  0.355726  0.031273
96 -0.070280  1.416508 -0.572036
97 -0.900802 -0.304065 -0.099777
98  0.568253 -0.698200 -0.303156
99  0.545258 -0.511511  0.712762

[100 rows x 3 columns]

In [75]:
df.iplot()

In [76]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [77]:
df1

0
0   94
1   43
2   60
3    9
4   57
..  ..
95  77
96  91
97  69
98  79
99  14

[100 rows x 1 columns]

In [78]:
df1.iplot()

In [79]:
df1

0
0   94
1   43
2   60
3    9
4   57
..  ..
95  77
96  91
97  69
98  79
99  14

[100 rows x 1 columns]

In [80]:
df

A         B         C
0   0.438656 -0.503832 -2.042863
1  -0.044595  1.072661  0.488996
2   1.408702 -1.083059  1.868867
3  -0.121024 -2.399767  0.239453
4   0.408174  0.726992  0.489874
..       ...       ...       ...
95 -2.729132  0.355726  0.031273
96 -0.070280  1.416508 -0.572036
97 -0.900802 -0.304065 -0.099777
98  0.568253 -0.698200 -0.303156
99  0.545258 -0.511511  0.712762

[100 rows x 3 columns]

In [81]:
df.iplot(x = 'A' , y = 'B',mode = 'markers')

In [82]:
df2 = sns.load_dataset('titanic')

In [83]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [84]:
df2.iplot(x = 'age' , y ='fare',mode = 'markers' )

In [85]:
df2.iplot(x = 'age' , y ='pclass',mode = 'markers' )

In [86]:
df2.iplot(x = 'fare' , y ='pclass',mode = 'markers' )

In [87]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [88]:
df2.iplot(kind = 'bar' , x = 'sex' , y = 'survived')